version: "3.8"
services:
  energy-management-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 18juNi91.
      POSTGRES_DB: energy_management
    volumes:
      - energy-management-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  EnergyManagement:
    image: energy-management-api:v1.0
    depends_on:
      - energy-management-db
    ports:
      - "8080:8080"

  carlease-front:
    image: energy-management-fe
    ports:
      - "1000:80"

volumes:
  energy-management-db:
    driver: local
